config/routes.rb
Rails.application.routes.draw do
  get 'prueba', to: 'home#prueba'
  get 'historial', to: 'home#historial'
  get 'usuarios', to: 'users#index'
  resources :appointments
  resources :consults
  get 'citasAjax', to:"home#citasAjax"
  get 'procAjax', to:"home#procAjax"
  root 'home#index'
      devise_for :users
      as :user do
      get '/users/sign_out' => 'devise/sessions#destroy'
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.has_role? :admin
      can :manage, :all
    else
    can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/consult.rb
class Consult < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include Response
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?

  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    def create
        @appointment = Appointment.new appointment_params
        @appointment.save
        redirect_to '/historial'
    end

    private
    def appointment_params
        params.require(:appointment).permit(:procedimiento, :paciente, :dia, :hora, :disponible)
    end
end

app/controllers/concerns/response.rb
# app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/consults_controller.rb
class ConsultsController < ApplicationController
     def create
        @consult = Consult.new consult_params
        @consult.save
        redirect_to '/'
    end

    private
    def consult_params
        params.require(:consult).permit(:paciente, :procedimiento,  :pendiente)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def prueba
    end

    def index
        @appointments = Appointment.all
        
    end
    def citasAjax
        @appointments = Appointment.all.order(:dia, hora: :desc)
        json_response(@appointments)
    end
    def procAjax
        @consults = Consult.all
        json_response(@consults)
    end

    def historial

    end
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/historial.html.erb
<div class="row justify-content-center">
<div class="col-9">
      <div class="card border-light">
        <div class="card-header">Historial clínico</div>
        <div class="card-body text-dark row">
<div class="col-8">
          
          
          <h5 class="card-title">Procedimientor realizados</h5>
          <p class="card-text" >
          <div v-for="item in t3">
<div v-if="item.paciente=='<%=current_user.name%>' && item.pendiente==false">
<p>{{item.procedimiento}}</p>
</div>
          </div>
          </p>
          <h5 class="card-title">Procedimientos pendientes</h5>
          <p class="card-text" ><div v-for="item in t3">
          <div v-if="item.paciente=='<%=current_user.name%>' && item.pendiente==true">
<p>{{item.procedimiento}}</p>
</div>
          </div>
          </p>
</div>
<div class="col-3 card">
<%= image_tag("Cons12.png", class: "card-img-top") %>

</div>


        </div>
      </div>
    </div>
    </div>

app/views/home/index.html.erb
<div style="height: 91.5vh;">
  <% if !user_signed_in? %>
  <div class="jumbotron h-100" style="margin-bottom:0px;padding: 6rem 4rem;z-index:1;">
    <h1 class="display-4">Consultorio Dental</h1>
    <p class="lead">Sistema desarrollado con Ruby, Rails y Bootstrap.</p>
    <hr class="my-4">
    <p>Accede o registrate.</p>
    <a class="btn btn-primary btn-lg" href="/users/sign_up" role="button">Registrarse</a>
  </div>
  <%else%>
  <br>


  <% if !current_user.is_medic?%>
  <br>
  <div class="row justify-content-center">


    <div class="col-12">
      <div class="card border-light">
        <div class="card-header">Haz una cita</div>
        <div class="card-body row">

          <div class="col-8">
            <h5 class="card-title">Seleccione el día de la cita</h5>
            Fecha
            <%= form_for :appointment, url: appointments_path do |f| %>

            <datetime type="date" v-model="dateEmpty" value-zone="America/Mexico_City" input-class="my-class form-control"
              :format="dateFormat" :phrases="{ok: 'Continuar', cancel: 'Salir'}" :min-datetime="now" :max-datetime="maxDate"
              :week-start="1" auto name="appointment[dia]" id="appointment_dia"></datetime>
            <small class="form-text text-muted description" slot="after">No hay citas los días domingo.</small>

            <div v-if="fechaCita">
              <br>Hora
              <datetime type="time" v-model="timeEmpty" value-zone="America/Mexico_City" input-class="my-class form-control"
                :format="timeFormat" :phrases="{ok: 'Continuar', cancel: 'Salir'}" :hour-step="1" :minute-step="30"
                use12-hour auto name="appointment[hora]" id="appointment_hora"></datetime>
              <small class="form-text text-muted description" slot="after">El horario es
                de lunes a viernes de 9:00 a 18:00hrs y sábados de 9:00 a 13:00hrs.</small>
              <div class="row">
                <div class="actions">
                  <!--<%= f.text_field :procedimiento %>-->
                  <input name="appointment[procedimiento]" id="appointment_procedimiento" type="hidden" value="Revisión general">
                  <input name="appointment[disponible]" id="appointment_disponible" type="hidden" value="T">
                  <input name="appointment[paciente]" id="appointment_paciente" type="hidden" value="<%=current_user.name%>">

                </div>
              </div>
              <div v-if="appoOk" class="col-2 float-right">
                <br>
                <%= f.submit "Aceptar", class:"btn btn-primary" %>
              </div>
            </div>

            <%end%>
          </div>

          <div class="col-4">
            <div class="list-group">
              <span href="#" class="list-group-item list-group-item-warning flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">Horarios no disponibles</h5>

                </div>
                <!-- <%- @appointments.each do |appointment| %>                    
                  
                    <div v-show="fechaCita"> # <%= appointment.dia %> -> <%= appointment.hora %>  <br></div>
                     
                  <% end %>
                  -->


                <div v-for="item in t1">

                  <div class="list-group-item" v-show="item.dia.replace(/(\d{2})\/(\d{2})\/(\d{4})/,'$3-$2-$1')==dateEmpty.slice(0, 10)">#
                    {{item.hora}}<br></div>
                </div>



              </span>
              <a href="#" class="list-group-item list-group-item-success flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                  <h5 class="mb-1">List group item heading</h5>
                   </div> <%=content_tag :div, class:
                      "appointments_class" , id: "horariosId" , data: {appointments: @appointments} do %>

                      <% end %>
                  
              </a>

            </div>
          </div>

        </div>
      </div>
    </div>




  </div>

  <%else%>

  <div class="row justify-content-center" style="margin-top:0px;">


    <div class="col-3">
      <div class="card border-info" style="max-width: 18rem;">
        <div class="card-header">Citas del día {{isoedDate}}</div>
        <div class="card-body text-info">
          <h5 class="card-title">Hoy:</h5>
          <div v-for="item in t1">
            <div class="list-group-item" @click="newConsulta(item)" v-if="item.dia==now.slice(0, 10)">
              <a href="#" v-if="item.disponible && !aFinished">
              
                <h4 style="margin-bottom: 0px;"># {{item.hora}}</h4>
                &nbsp {{item.paciente}}<br></div>
            </a>
          </div>
        </div>

      </div>
    </div>


    <div class="col-9">
      <div class="card border-light">
        <div class="card-header">Consulta</div>
        <div class="card-body text-dark row">
<div class="col-8">
          <h5 class="card-title">Datos de la cita</h5>
          <div class="card-text" v-if="appoOk">
          <p> {{'Nombre de paciente: ' + activeAppo.paciente}} </p>
          
          <p v-if="t3.length<=1"> {{'Procedimiento: ' + activeAppo.procedimiento}} </p>
          <p v-else> {{'Procedimiento: ' + t3[0].procedimiento}} </p>
          <p> {{'Hora de cita: ' + activeAppo.hora}}</p></div>
          
          
          <h5 class="card-title">Historial</h5>
          <p class="card-text" v-if="appoOk">
          <div v-for="item in t3">
<div v-if="item.paciente==activeAppo.paciente && item.pendiente==false">
<p>{{item.procedimiento}}</p>
</div>
          </div>
          </p>
          <h5 class="card-title">Procedimientos pendientes</h5>
          <p class="card-text" v-if="appoOk"><div v-for="item in t3">
          <div v-if="item.paciente==activeAppo.paciente && item.pendiente==true">
<p>{{item.procedimiento}}</p>
</div>
          </div></p>
</div>
<div class="col-3 card">
<%= image_tag("Cons12.png", class: "card-img-top") %>

</div>
          <div v-if="appoOk">
            <%= form_for :consult, url: consults_path do |f| %>  
            <br>
            <div class="row no-gutters">
              <div class="col-2">
                <!--<%= f.submit "Nuevo procedimiento", class:"btn btn-primary" %>-->
                <button type="button" class="btn btn-primary" @click="newProcedimientosM=true">
                  Nuevo procedimiento
                </button>
              </div>
<input name="consult[pendiente]" id="consult_pendiente" type="hidden" value="F">
          <input name="consult[paciente]" id="consult_paciente" type="hidden" v-bind:value="activeAppo.paciente">
          <input name="consult[procedimiento]" id="consult_procedimiento" type="hidden" v-bind:value="activeAppo.procedimiento">
              <div class="col-2 offset-7">
                <%= f.submit "Terminar consulta", class:"btn btn-danger" %>
              </div>
            </div>
            <%end%>
          </div>

        </div>
      </div>

      <br>
      <div class="card border-light" v-if="newProcedimientosM">
        <div class="card-header">Nuevo procedimiento</div>
        <div class="card-body text-dark">
          <h6 class="card-title">Nombre</h6>
          <p class="card-text">   
          <%= form_for :consult, url: consults_path do |f| %>                 
          <input name="consult[procedimiento]" id="consult_procedimiento" class="form-control">
          <small class="form-text text-muted description" slot="after">Describe de forma específica que procedimiento es y a que area se aplica.</small>
          <input name="consult[pendiente]" id="consult_pendiente" type="hidden" value="T">
          <input name="consult[paciente]" id="consult_paciente" type="hidden" v-bind:value="activeAppo.paciente">
          
          </p>
          <div class="row no-gutters">
              <div class="col-2">
                <%= f.submit "Aceptar", class:"btn btn-primary" %>
                </div>
                <div class="offset-2 col-2">
                <button type="button" class="btn btn-secondary" @click="newProcedimientosM=false">
                  Cancelar
                </button>
              </div>
          </div>    
          <%end%>
        </div>
      </div>
    </div>

    



  </div>
  <%end%>


  <%end%>
</div>

<!--<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>¡Alerta!</strong> <a href="#" class="alert-link">Esto no</a> funciona todavía.
</div>-->

app/views/home/prueba.html.erb
<p class="alert"><%= notice %></p>
<p class="notice"><%= alert %></p>

<div class="row">
<h2>qwerr!!!!!!!</h2>
<div id='hello'>
   {{message}}
   <app></app>
   <datetime
  type="datetime"
  v-model="datetimeEmpty"
  input-class="my-class form-control"
  value-zone="America/New_York"
  :format="{ year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZoneName: 'short' }"
  :phrases="{ok: 'Continuar', cancel: 'Salir'}"
  :hour-step="1"
  :minute-step="30"
  :min-datetime="minDatetime"
  :max-datetime="maxDatetime"
  :week-start="7"
  use12-hour
  auto
  ></datetime>
   <datetime
  type="datetime"
  v-model="datetimeEmpty"
  input-class="my-class form-control"
  value-zone="America/New_York"
  :format="{ year: 'numeric', month: 'long', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZoneName: 'short' }"
  :phrases="{ok: 'Continuar', cancel: 'Salir'}"
  :hour-step="1"
  :minute-step="30"
  :min-datetime="minDatetime"
  :max-datetime="maxDatetime"
  :week-start="7"
  use12-hour
  auto
  ></datetime>
  <label for="startDate" slot="before">Titulo</label>
  <span class="description" slot="after">Descripcion</span></datetime>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Consultorio Dental</title>
  <%= csrf_meta_tags %>
<link rel="stylesheet" type="text/css" href="../../../node_modules/vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href= '../../../node_modules/vue-datetime/dist/vue-datetime.min.css'></link>


  <!--<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>-->
  <%= javascript_pack_tag 'hello_vue' %>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="/">Consultorio Dental</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Inicio <span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed_in?%>
        <% if !current_user.is_medic?%>        
        <li class="nav-item">
          <a class="nav-link" href="/historial">Historial Médico</a>
        </li>
        <%else%>        
        <!--<li class="nav-item">
          <a class="nav-link" href="#">Consultas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Historial Médico</a>
        </li>-->
        <%end%>
        <%end%>

      </ul>
      <div class="my-2 my-lg-0">

        <ul class="navbar-nav mr-auto">
          <%if alert%>
          <li class="nav-item">
            <span class="nav-link"><kbd>
                <%= alert %></kbd></span>
          </li>
          <%end%>
          <%if notice%>
          <li class="nav-item">
            <span class="nav-link"><kbd>
                <%= notice %></kbd></span>
          </li>
          <%end%>
          <% if user_signed_in? %>

          <li class="nav-item active">
            <span class="nav-link">
              <%= current_user.name %></span>
          </li>

          <li class="nav-item active">
            <span class="nav-link">
              <%= link_to 'Salir', destroy_user_session_path, method: :delete, class:"text-white" %>
            </span>
          </li>
          <% else %>

          <li class="nav-item active">
            <a class="nav-link" href="/users/sign_in">Acceder </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/users/sign_up">Registrarse</a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid" id='hello'>

    <%= yield %>
  </div>
  
</body>

</html>